### ISSUE TITLE
Add http://viewdocs.io/<username>/<repository>

### ISSUE THREAD

**Issue by hugopeixoto** [progrium/viewdocs#55]
[We previously discussed the lack of SSL](https://github.com/progrium/viewdocs/issues/54), and how it's not possible to do it in heroku.

Something that could work is to change the URL structure to something like what's used by other projects:

- https://gitter.im/mustache/mustache
- http://travis-ci.org/github/mustache/mustache
- https://viewdocs.io/progrium/viewdocs

This would remove the requirement for wildcard domains and certificates, making SSL easier to setup.

If breaking existing links under `//viewdocs.io` is a problem, you could use a fixed subdomain to work around it: `https://secure.viewdocs.io/progrium/viewdocs`. Unsure what a good subdomain would be, though.

**Comment by hugopeixoto** [comment]
To push this along, I've created a pull request: #56.

It seems that the issue I mentioned, breaking links under `//viewdocs.io`, is not an issue, as there are no links in the top level domain. Only `/` redirects to `progrium.viewdocs.io/viewdocs/`.

**Comment by josegonzalez** [comment]
Thinking about this further, I don't think I like it. If we then give an SSL cert to it, we can get all the docs for _every_ project blacklisted on Google due to someone putting up some fishing site. Yeah the chance is low but scammers are always willing to screw things up for everyone.

Given the fact that I'm now getting the domain name, I think we can close this.
